services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: regression_eye
      POSTGRES_USER: re
      POSTGRES_PASSWORD: re
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
